<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Licenses.licx" />
    <None Update="Demo.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.RichEdit.Export" Version="24.2.*" />
    <PackageReference Include="DevExpress.Wpf.Reporting" Version="24.2.*" />
    <PackageReference Include="DevExpress.Wpf.PdfViewer" Version="24.2.*" />
    <PackageReference Include="DevExpress.Wpf.Themes.Win11Light" Version="24.2.*" />
	  <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
</Project>
