<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>
  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Licenses.licx" />
    <None Update="Demo.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.RichEdit.Export" Version="24.2.*" />
    <PackageReference Include="DevExpress.Wpf.Reporting" Version="24.2.*" />
    <PackageReference Include="DevExpress.Wpf.PdfViewer" Version="24.2.*" />
    <PackageReference Include="DevExpress.Wpf.Themes.Win11Light" Version="24.2.*" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>